### ISSUE TITLE
Monitored item delivers errors in clients log.

### ISSUE THREAD

**Issue by antroa** [nauful/LibUA#16] opened 2020-05-06 10:59 UTC
Monitoring "Item\Trend 000001" with UAExpert delivers every second this log-messages in UAExpert's log output:

```
Error: Number of acknowledgement results (0) does not match number of acknowledgements (2)
Error: UaSessionPrivate::publishCallback - List of available sequence numbers is empty, at least current sequence number has to be available
```

**Comment by nauful** [comment] 2020-05-07 11:19
Fixed: https://github.com/nauful/LibUA/commit/4a2ee9a48438d8aceeca55840320a05c2cb440a6

**Comment by nauful** [comment] 2020-05-07 11:22
How do you reproduce this? Acknowledgements are being sent back, perhaps a configuration issue that I can investigate.

![image](https://user-images.githubusercontent.com/50109829/81288854-06c83900-902b-11ea-8376-0a077420ccc8.png)

**Comment by nauful** [comment] 2020-05-14 13:47
Closing, could not reproduce.

**Closed by nauful** 2020-05-14 13:47 UTC
