### ISSUE TITLE
acknowledgement errors

### ISSUE THREAD

**Issue by Ttberg** [nauful/LibUA#63] opened 2021-08-05 07:01 UTC
![acknowledgement errors](https://user-images.githubusercontent.com/63335009/128305906-1a8f5817-13ce-48ec-b0f4-cae7e6d2d385.PNG)

connecting UaExpert to the LibUA server gives lots of acknowledgement errors

**Comment by nauful** [comment] 2021-08-05 20:19
This is expected behaviour due to differences in timing. The end total of acknowledgements matches the expected number: https://github.com/nauful/LibUA/issues/43#issuecomment-800686600

This could be fixed by making publishes synchronous, but this would severely reduce performance when publishing a huge number of points per second (primary use case for me). You might take another look at it, but I didn't find an elegant fix other than making the whole publishing system synchronous (i.e. publish acknowledgement publishes the next from a queue waiting, if available, instead of the async notification queue).

**Closed by nauful** 2021-08-05 20:19 UTC
